WIP: Dockerfile: install clang-check dependencies
Running `idf_tools.py install xtensa-clang` with the current ESP-IDF
version installs xtensa-esp32-elf-llvm12_0_1-esp-12.0.1-20210914. Let's
install the same major version of clang-tidy in our container so we can
use IDF's clang tidy features.

To run clang-tidy:
./utils.sh clang-check --run-clang-tidy-py /usr/lib/llvm-12/share/clang/run-clang-tidy.py

Unfortunately this trips over several missing include files, and I fail
to find how to fix this:

/opt/esp/idf/components/newlib/platform_include/endian.h:51:10: error: 'machine/endian.h' file not found [clang-diagnostic-error]

/opt/esp/idf/components/xtensa/esp32s3/include/xtensa/config/core.h:44:10: error: '../hal.h' file not found [clang-diagnostic-error]

Also tried running like this but same problem:

idf_clang_tidy --xtensa-include-dir /opt/esp/tools/xtensa-clang/12.0.1-d9341b81fc/xtensa-esp32-elf-clang/xtensa-esp32-elf/include /willow/ --run-clang-tidy-py /usr/lib/llvm-12/share/clang/run-clang-tidy.py

Related: https://github.com/espressif/esp-idf/issues/6868